# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06a1f7313ad7fa859f9579c7e56a738428c54568a147a599569137c517a25c72e7e138909f7281b0e3bd4d05f2f1dbbd596f988a4ccba58eabf2fd7dae0e85ac

test:
  secret_key_base: 8eb18069326166a7b044f8391319c5bb50ec38e6d4d736ef71f0219b6507726b838f141c5960346c556244d432b90da89a8f0d71fd33555324f93bb68a14c9b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
